.TH "depfinder" 1 "12/13/2009" "George Vlahavas"

.SH NAME
.P
depfinder \- a tool that finds dependencies of slackware packages

.SH SYNOPSIS
.P
\fBdepfinder\fR [\fIOPTIONS\fR] \fIPACKAGE\fR or \fIPACKAGING\-DIRECTORY\fR

.SH DESCRIPTION
.P
\fBdepfinder\fR is a tool that finds the dependencies of Slackware packages.
It examines binary files in the packages and the libraries they link to and
reports the packages these libraries belong to in a dependency list.
The dependencies are by default being output to a comma separated
list without version information, but there are options to output
dependencies with version information and to a file: a .dep file
with a comma separated list without version information, or a
\fIslack\-required\fR file that includes version information.

.P
\fBdepfinder\fR can check \fI.tgz\fR, \fI.tbz\fR, \fI.tlz\fR and \fI.txz\fR
packages for dependencies
but you can also point it to a packaging directory where you have the
package contents extracted.

.P
\fBdepfinder\fR uses \fBldd\fR for discovering dependencies, so it will only find
dependencies of binary files. Scripts (bash,
python, etc) are not supported in any way.

.P
If a certain library is included in more than one packages, then all
packages that include it will be listed in one entry using an "or"
statement (which is expressed with the pipe symbol: "|"). For example a
dependency for a library that is included in both \fIopenssl\fR and
\fIopenssl\-solibs\fR packages will be output as:
\fIopenssl|openssl\-solibs\fR.

.P
You need to have all required dependencies for any package you run
\fBdepfinder\fR on installed in your system. That will of course always be
the case when you are building your own packages. In case there is a
library that is required by a package you run \fBdepfinder\fR on that is
missing from your system, \fBdepfinder\fR will report the missing library
and will not generate a dependency list.

.P
\fBdepfinder\fR also has support for running multiple jobs which makes it
a \fBlot\fR faster on PCs with multiple CPUs/cores.

.SH OPTIONS
.P
\fB\-f\fR,
Output dependencies to a file instead of stdout. By default it creates a
\&.dep file with a comma separated list of dependencies without version
information. See also \fB\-s\fR.

.P
\fB\-s\fR,
Outputs dependencies including version information. Dependencies will be
listed in the format following this example: "zlib >= 1.2.3\-i486\-2". If
combined with \fB\-f\fR, it creates a slack\-required file which can be
placed inside the package under the \fIinstall\fR directory.

.P
\fB\-a\fR,
Checks all files in the directory tree instead of following the FHS. If
\fB\-a\fR is not used then depfinder looks for binary files only under
\fI/sbin\fR ,\fI/usr/sbin\fR, \fI/usr/bin\fR, \fI/bin\fR, \fI/usr/libexec\fR and
\fI/usr/lib\fR, \fI/lib\fR or \fI/usr/lib64\fR, \fI/lib64\fR for 32\-bit and
64\-bit architectures respectively. If \fB\-a\fR is used, then depfinder
searches for files dynamically linking to libraries anywhere inside the
package. This option could be usefull if the installation scripts put
binaries in a non\-standard location.

.P
\fB\-j\fR \fIjobs\fR,
The number of parallel depfinder jobs to run. depfinder will finish
considerably faster if this matches exactly the number of your
CPUs/cores (default number of jobs: 1)

.SH GENERAL OPTIONS
.P
\fB\-v\fR,
Shows version information for depfinder and exits.

.P
\fB\-h\fR,
Prints a usage message briefly summarizing all command\-line options
and exits.

.SH AUTHORS
.P
depfinder was written by George Vlahavas <vlahavas~at~gmail~dot~com>

.SH SEE ALSO
.P
\fBldd\fR(1)


.\" man code generated by txt2tags 2.5 (http://txt2tags.sf.net)
.\" cmdline: txt2tags depfinder.t2t

